### ISSUE TITLE
discussion: deprecation and removal of io.js recipes

### ISSUE THREAD

**Issue by imyller** [imyller/meta-nodejs#23]
I'm currently considering removing io.js recipes from meta-nodejs.

Io.js is no longer receiving upstream updates and is replaceable with Node.js 4.x LTS for most users. 

If io.js recipes are removed from this layer, I'll probably add an package alias `iojs` to Node.js LTS recipe so that possible dependencies to `iojs` package will function.

**Comment by imyller** [comment]
Request for comments.

/cc @bachp @jmesmon @geomatsi @gsikorski @fladi

**Comment by bachp** [comment]
I also think for iojs users and update to Node.js 4.x is feasible.

**Comment by codyps** [comment]
My use case was never updated to `iojs`, so I don't have any issue with this.

**Comment by geomatsi** [comment]
My use case is trivial: I only experimented with embedded nodejs builds and didn't use iojs at all. In general, IIUC iojs is going to be discontinued. So removing those recipes will help to make the right choice for new users.

**Comment by imyller** [comment]
Thank you for your feedback. Implemented this change in PR #25
