### ISSUE TITLE
How to use this layer for native only

### ISSUE THREAD

**Issue by mschuckmann** [imyller/meta-nodejs#28]
I may be missing something here, I want to use this layer native only. 
I have a recipe for a web-app that needs to get built using npm, bower, and grunt and the result installed on the image. The image doesn't need npm,bower or grunt only the build system. 
Looking at the npm class node always gets added to RDPENDS.

**Comment by imyller** [comment]
You can put `DEPENDS` on `nodejs-native` to get native (but "cross-compiling") Node.js and npm. `npm` and `npm-install` bitbake classes included in this layer automatically depend on `nodejs-native` and provide some helper commands and build tasks.

You do not need to create `RDEPENDS` run-time dependencies to any of the packages.

I personally have a use-case where web-app is built the way you described and results are packaged for target system.

**Comment by imyller** [comment]
> Looking at the npm class node always gets added to RDPENDS.

That is true. As soon as I have some time, I'll look in to providing build system only helper classes that are more focused on running build automation tools.

**Comment by imyller** [comment]
This should be fixed now with commit 247732c8fcf80c96c8e403204005f384186e3738

There is no longer forced RDEPENDS to Node.js package when using `npm` class.
