### ISSUE TITLE
reason for `--without-snapshot ` in configure

### ISSUE THREAD

**Issue by mbroadst** [imyller/meta-nodejs#31]
Hi, I'm trying to cross-compile rethinkdb using yocto which includes a static build of v8, and I've been running into problems with the generated snapshot utility. I noticed in your recipes that you disable the snapshot, is that because you couldn't get it working? Just wondering if you could help with some insight here, thanks!

**Comment by imyller** [comment]
Yes, the generated `mksnapshot` also gets cross-compiled and you'd need native version of it for v8 snapshot build to succeed.

Here is more info about current situation with v8 snapshots and Node.js cross-compiling:
https://github.com/nodejs/node/issues/4860

I have an option to compile `nodejs-native` as a dependency before `nodejs` recipe, and then copying over the `mksnapshot` natively compiled for the build host. This approach should work but it's bit ugly and requires "unnecessary" compilation of the native package every time target package gets updated.

There is some discussion about exporting `CC_host` and `CXX_host` environment variables before building allowing some kind of partial cross-compilation, but I havent tried this approach yet with Yocto packages. (https://github.com/nodejs/build/issues/266#issuecomment-171660151)

**Comment by mbroadst** [comment]
@imyller hmm interesting, so potentially we could just modify the gyp file for building `mksnapshot` to override the compiler used. I'll give it a shot later today and report back, thanks

**Comment by mbroadst** [comment]
@imyller hey, so I did some quick read throughs of the build system and tried this out, which seems to work:

```
do_configure () {
  export LD="${CXX}"
  alias g++="${CXX}"
  GYP_DEFINES="${GYP_DEFINES}" export GYP_DEFINES
  ./configure   --prefix="${prefix}" \
                --dest-cpu="${@map_dest_cpu(d.getVar('TARGET_ARCH', True), d)}" \
                --dest-os=linux ${ARCHFLAGS} \
                ${EXTRA_OECONF}
  unalias g++

  # testing with-snapshot
  sed -i "s#'want_separate_host_toolset%': 0#'want_separate_host_toolset%': 1#g" common.gypi
  sed -i "s#'want_separate_host_toolset': 0#'want_separate_host_toolset': 1#g" config.gypi
}
```

specifically I modified the `do_configure` to enable snapshots (the default, so just remove `--without-snapshot`), and then I explicitly defined `want_separate_host_toolset` to 1 with sed. I couldn't figure out how to define it through the configure script maybe you have some insight there.

So it builds fine for the native and host packages at least for x64 <=> qemux86_64. There are a number of concerns/questions/thoughts I have at this point:
- I think this is probably needlessly creating two toolchains in _at very least_ the native package, so it should probably be removed for the native's `do_configure`
- As I mentioned above sed probably isn't the ideal solution here
- I think this flag enables more work than just what's needed for `mksnapshot` though I'm not quite sure _what_ exactly - as I'm just passing through quickly here
- I have done absolutely no testing on anything other than my current environment, which doesn't even target real hardware presently (currently just building a VM image during early development)

HTH

**Comment by imyller** [comment]
Great work!

I see that there is some logic for defining `want_separate_host_toolset` in Node.js `configure`:

https://github.com/nodejs/node/blob/v5.10.1/configure#L694

We might be able to avoid using sed by specifically defining `host_arch` and `target_arch` for `configure`?

**Comment by mbroadst** [comment]
I tried that approach, and I'm sure I missed something, but this value was set explicitly no matter what I did

**Comment by imyller** [comment]
ref #34

**Comment by imyller** [comment]
V8 snaphots are being worked on in `master` branch for Node.js v7 and already works with certain limitations.

There are unresolved issues with cross-compilation dependencies affecting `mksnapshot` and `mkpeephole` build steps - discussed in #56

**Comment by markrey** [comment]
@mbroadst Is it possible to share your Yocto Layer file for rethinkdb? (if not confidential)
I am struggling to do since last few days :)

**Comment by mbroadst** [comment]
@markrey sure here you go: 
https://gist.github.com/mbroadst/74d0d0f642dfccd459d89d6d2e61b2fd
https://gist.github.com/mbroadst/5f5dc8d0bd606e2f136a39db2d9793d4
https://gist.github.com/mbroadst/39bb312c6701b0ba6c913b1b14bd436b
https://gist.github.com/mbroadst/ef96414b1485c13158fd8069df29a8e3
https://gist.github.com/mbroadst/37b81a0370fef807da163b8c1a49b447
https://gist.github.com/mbroadst/3b6052b01a04553198e898c7469c7273
https://gist.github.com/mbroadst/0262ad9be21fc974b366aee25102e22c

**Comment by markrey** [comment]
@mbroadst Thank you very much! Really do appreciate it! Long night tonight to compile this :)

**Comment by markrey** [comment]
@mbroadst one file 0004-remove-no-registry-flag-for-npm-install.patch is missing. Do you have it available by any chance?

**Comment by mbroadst** [comment]
@markrey oops  yeah here it is: https://gist.github.com/mbroadst/b4f4b11d22e8fd9529b4f01507f31845
